// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using banthietbidientu.Data;

#nullable disable

namespace TestDoAn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128143254_FixSeedDataForPhoneNumber")]
    partial class FixSeedDataForPhoneNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("banthietbidientu.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaDon");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("banthietbidientu.Models.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PhieuNhapId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhieuNhapId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("banthietbidientu.Models.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTraLoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("Sao")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaDon");

                    b.HasIndex("SanPhamId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("banthietbidientu.Models.DoanhThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LoiNhuan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DoanhThus");
                });

            modelBuilder.Entity("banthietbidientu.Models.DonHang", b =>
                {
                    b.Property<string>("MaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PhiShip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDon");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("banthietbidientu.Models.GioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("banthietbidientu.Models.LichSuMuaHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiDonHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("LichSuMuaHangs");
                });

            modelBuilder.Entity("banthietbidientu.Models.LichSuNhapHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.ToTable("LichSuNhapHangs");
                });

            modelBuilder.Entity("banthietbidientu.Models.PhieuNhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PhieuNhaps");
                });

            modelBuilder.Entity("banthietbidientu.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Điện thoại",
                            Description = "Điện thoại thông minh cao cấp với màn hình tràn viền.",
                            GiaNhap = 500.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Galaxy+X",
                            MoTa = "Smartphone Galaxy X sở hữu thiết kế đột phá...",
                            Name = "Smartphone Galaxy X",
                            Price = 699.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 2,
                            Category = "Laptop",
                            Description = "Laptop hiệu năng cao cho công việc chuyên nghiệp.",
                            GiaNhap = 1000.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Laptop+Pro",
                            MoTa = "Laptop Pro 15 được trang bị chip xử lý mới nhất...",
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 3,
                            Category = "Phụ kiện",
                            Description = "Tai nghe không dây chống ồn chủ động.",
                            GiaNhap = 150.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Headphones",
                            MoTa = "Trải nghiệm âm thanh đỉnh cao với Wireless Headphones Elite...",
                            Name = "Wireless Headphones Elite",
                            Price = 199.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 4,
                            Category = "Đồng hồ",
                            Description = "Đồng hồ thông minh theo dõi sức khỏe toàn diện.",
                            GiaNhap = 300.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Smartwatch",
                            MoTa = "Smartwatch Series 7 hỗ trợ đo nhịp tim, SpO2...",
                            Name = "Smartwatch Series 7",
                            Price = 399.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 5,
                            Category = "TV",
                            Description = "TV 4K sắc nét, trải nghiệm điện ảnh tại gia.",
                            GiaNhap = 600.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Smart+TV",
                            MoTa = "Màn hình 55 inch độ phân giải 4K HDR...",
                            Name = "4K Smart TV 55\"",
                            Price = 799.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 6,
                            Category = "Phụ kiện",
                            Description = "Loa Bluetooth di động âm bass mạnh mẽ.",
                            GiaNhap = 100.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Speaker",
                            MoTa = "Bluetooth Speaker nhỏ gọn, pin trâu...",
                            Name = "Bluetooth Speaker",
                            Price = 149.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 7,
                            Category = "Console",
                            Description = "Máy chơi game thế hệ mới, đồ họa đỉnh cao.",
                            GiaNhap = 400.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Console",
                            MoTa = "Gaming Console X hỗ trợ chơi game 4K 120fps...",
                            Name = "Gaming Console X",
                            Price = 499.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 8,
                            Category = "Phụ kiện",
                            Description = "Chuột không dây tiện lợi, độ nhạy cao.",
                            GiaNhap = 30.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Mouse",
                            MoTa = "Thiết kế Ergonomic giúp cầm nắm thoải mái...",
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 9,
                            Category = "Phụ kiện",
                            Description = "Sạc dự phòng dung lượng lớn, sạc nhanh.",
                            GiaNhap = 20.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Charger",
                            MoTa = "Dung lượng 10000mAh sạc được nhiều lần...",
                            Name = "Portable Charger 10000mAh",
                            Price = 29.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tablet",
                            Description = "Máy tính bảng mỏng nhẹ, hiệu năng tốt.",
                            GiaNhap = 350.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Tablet",
                            MoTa = "Màn hình Retina sắc nét, chip xử lý mạnh mẽ...",
                            Name = "Tablet Air 10",
                            Price = 499.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 11,
                            Category = "Phụ kiện",
                            Description = "Bàn phím không dây gõ êm, kết nối ổn định.",
                            GiaNhap = 50.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Keyboard",
                            MoTa = "Tương thích nhiều thiết bị, hành trình phím tốt...",
                            Name = "Wireless Keyboard",
                            Price = 79.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 12,
                            Category = "Camera",
                            Description = "Camera hành trình quay 4K chống rung.",
                            GiaNhap = 200.00m,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Camera",
                            MoTa = "Quay video 4K 60fps, chống nước...",
                            Name = "Action Camera 4K",
                            Price = 249.99m,
                            SoLuong = 1000
                        });
                });

            modelBuilder.Entity("banthietbidientu.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Admin, TP.HCM",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FullName = "Quản Trị Viên",
                            Gender = "Male",
                            Password = "password",
                            PhoneNumber = "0901234567",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường User, Hà Nội",
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@example.com",
                            FullName = "Nguyễn Văn A",
                            Gender = "Male",
                            Password = "password",
                            PhoneNumber = "0909876543",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("banthietbidientu.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiThongBao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("banthietbidientu.Models.YeuCauThuMua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("YeuCauThuMua");
                });

            modelBuilder.Entity("banthietbidientu.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("banthietbidientu.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("banthietbidientu.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("banthietbidientu.Models.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("banthietbidientu.Models.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTiets")
                        .HasForeignKey("PhieuNhapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("banthietbidientu.Models.SanPham", "SanPham")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("banthietbidientu.Models.DanhGia", b =>
                {
                    b.HasOne("banthietbidientu.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("banthietbidientu.Models.SanPham", "SanPham")
                        .WithMany("DanhGias")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("banthietbidientu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("banthietbidientu.Models.DonHang", b =>
                {
                    b.HasOne("banthietbidientu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("DonHangs")
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("banthietbidientu.Models.GioHang", b =>
                {
                    b.HasOne("banthietbidientu.Models.SanPham", "SanPham")
                        .WithMany("GioHangs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("banthietbidientu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("banthietbidientu.Models.LichSuMuaHang", b =>
                {
                    b.HasOne("banthietbidientu.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("banthietbidientu.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("banthietbidientu.Models.LichSuNhapHang", b =>
                {
                    b.HasOne("banthietbidientu.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("banthietbidientu.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("banthietbidientu.Models.PhieuNhap", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("banthietbidientu.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("DanhGias");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("banthietbidientu.Models.TaiKhoan", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
