// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using banthietbidientu.Data;

#nullable disable

namespace TestDoAn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250724114506_AddCategoryToSanPham")]
    partial class AddCategoryToSanPham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestDoAn.Models.GioHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("TestDoAn.Models.LichSuMuaHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("LichSuMuaHangs");
                });

            modelBuilder.Entity("TestDoAn.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Galaxy+X",
                            Name = "Smartphone Galaxy X",
                            Price = 699.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Laptop+Pro",
                            Name = "Laptop Pro 15",
                            Price = 1299.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Headphones",
                            Name = "Wireless Headphones Elite",
                            Price = 199.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Smartwatch",
                            Name = "Smartwatch Series 7",
                            Price = 399.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Smart+TV",
                            Name = "4K Smart TV 55\"",
                            Price = 799.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Speaker",
                            Name = "Bluetooth Speaker",
                            Price = 149.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Console",
                            Name = "Gaming Console X",
                            Price = 499.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Mouse",
                            Name = "Wireless Mouse",
                            Price = 49.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Charger",
                            Name = "Portable Charger 10000mAh",
                            Price = 29.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Tablet",
                            Name = "Tablet Air 10",
                            Price = 499.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Keyboard",
                            Name = "Wireless Keyboard",
                            Price = 79.99m,
                            SoLuong = 1000
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://via.placeholder.com/300x200?text=Camera",
                            Name = "Action Camera 4K",
                            Price = 249.99m,
                            SoLuong = 1000
                        });
                });

            modelBuilder.Entity("TestDoAn.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Admin, TP.HCM",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FullName = "Quản Trị Viên",
                            Gender = "Male",
                            Password = "password",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường User, Hà Nội",
                            DateOfBirth = new DateTime(1995, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@example.com",
                            FullName = "Nguyễn Văn A",
                            Gender = "Male",
                            Password = "password",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("TestDoAn.Models.GioHang", b =>
                {
                    b.HasOne("TestDoAn.Models.SanPham", "SanPham")
                        .WithMany("GioHangs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDoAn.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("GioHangs")
                        .HasForeignKey("UserId");

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TestDoAn.Models.LichSuMuaHang", b =>
                {
                    b.HasOne("TestDoAn.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestDoAn.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("TestDoAn.Models.SanPham", b =>
                {
                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("TestDoAn.Models.TaiKhoan", b =>
                {
                    b.Navigation("GioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
